#!/usr/bin/env python3
"""
generate_journal_sitemap.py — sitemap.xml + robots.txt for the JOURNAL site
(www.oftmw.com), where the journal is served at the domain root and articles
live at /post/<slug>/ (matching the original Wix URLs). Output goes inside
journal/ so it's served at www.oftmw.com/sitemap.xml after the Cloudflare Pages
deploy (publish dir = journal/).

  python3 generate_journal_sitemap.py
"""
import json, os, subprocess, datetime, html

BASE   = "https://www.oftmw.com"
WORKER = "https://tmw.jake-ab7.workers.dev"
OUT_DIR = "journal"

def fetch_posts():
    raw = subprocess.check_output(["curl", "-s", f"{WORKER}/posts?limit=2000&status=published"], timeout=90)
    return json.loads(raw).get("items", [])

def iso(ts):
    if not ts:
        return None
    try:
        return datetime.datetime.fromtimestamp(int(ts), datetime.timezone.utc).strftime("%Y-%m-%d")
    except Exception:
        return str(ts)[:10]

def url_tag(loc, lastmod=None, priority="0.6", changefreq="weekly", images=None):
    """Standard <url> entry with optional <image:image> children for the
    image sitemap extension — Google Image Search uses these to discover
    every project rendering on the site. images = [(loc, caption), ...]."""
    s = f"  <url>\n    <loc>{html.escape(loc)}</loc>\n"
    if lastmod:
        s += f"    <lastmod>{lastmod}</lastmod>\n"
    s += f"    <changefreq>{changefreq}</changefreq>\n    <priority>{priority}</priority>\n"
    if images:
        for img_loc, img_caption in images:
            if not img_loc: continue
            s += "    <image:image>\n"
            s += f"      <image:loc>{html.escape(img_loc)}</image:loc>\n"
            if img_caption:
                s += f"      <image:caption>{html.escape(img_caption)}</image:caption>\n"
            s += "    </image:image>\n"
    s += "  </url>\n"
    return s

def _collect_project_images() -> dict[str, list[tuple[str,str]]]:
    """Walk projects-flat.json and return { project_slug → [(img_url, alt), ...] }.
    Used to inject image:image children into the /projects/<slug>/ URL entries
    so Google's Image Search can discover every project rendering."""
    out: dict[str, list[tuple[str,str]]] = {}
    try:
        with open('projects-flat.json', encoding='utf-8') as f:
            projects = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return out
    for p in projects:
        slug = (p.get('Slug') or '').strip()
        if not slug: continue
        imgs: list[tuple[str,str]] = []
        title = (p.get('Title') or '').strip()
        city  = (p.get('City') or '').strip()
        caption = f'{title} in {city}' if title and city else title
        for field in ('ImageURL', 'Image2', 'Image3', 'Image4', 'Image5'):
            u = (p.get(field) or '').strip()
            if u: imgs.append((u, caption))
        if imgs: out[slug] = imgs
    return out

def main():
    posts = fetch_posts()
    today = datetime.date.today().strftime("%Y-%m-%d")
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n          xmlns:image="http://www.google.com/schemas/sitemaps-image/1.1">']

    # Pre-load project images so we can attach them to /projects/<slug>/ entries
    project_imgs = _collect_project_images()
    out.append(url_tag(f"{BASE}/", today, "1.0", "daily"))
    for p in ("golf", "restaurants", "hotels"):
        out.append(url_tag(f"{BASE}/{p}/", today, "0.8", "weekly"))
    out.append(url_tag(f"{BASE}/media/", today, "0.6", "monthly"))
    out.append(url_tag(f"{BASE}/search/", today, "0.4", "monthly"))
    for it in posts:
        slug = it.get("slug")
        if not slug:
            continue
        # lastmod = last edit (updated_at) so edited posts get recrawled; fall
        # back to first-publish if updated_at is somehow missing.
        lastmod = iso(it.get("updated_at") or it.get("published_at"))
        out.append(url_tag(f"{BASE}/post/{slug}/", lastmod, "0.7", "monthly"))

    # SEO programmatic market pages: every URL written by
    # generate_market_pages.py is listed in journal/markets/.urls.json so we
    # don't have to re-scan the filesystem here. /markets/ itself gets a
    # slightly higher priority than the leaves. All changefreq=weekly since
    # the underlying project data updates hourly.
    markets_count = 0
    manifest_path = f"{OUT_DIR}/markets/.urls.json"
    if os.path.exists(manifest_path):
        with open(manifest_path, encoding="utf-8") as f:
            mf = json.load(f)
        for url_path in mf.get("urls", []):
            prio = "0.7" if url_path == "/markets/" else "0.6"
            out.append(url_tag(f"{BASE}{url_path}", today, prio, "weekly"))
            markets_count += 1

    # Project pages (/projects/<slug>/) — these are generated by
    # generate_pages.py from projects-flat.json. Walk the directory once.
    # Each project entry carries its image renderings as image:image
    # children, which feeds Google Image Search.
    projects_count = 0
    proj_dir = f"{OUT_DIR}/projects"
    if os.path.isdir(proj_dir):
        for slug in sorted(os.listdir(proj_dir)):
            sub = os.path.join(proj_dir, slug)
            if not os.path.isdir(sub) or not os.path.isfile(os.path.join(sub, 'index.html')): continue
            imgs = project_imgs.get(slug, [])
            out.append(url_tag(f"{BASE}/projects/{slug}/", today, "0.7", "weekly", images=imgs))
            projects_count += 1

    # Firm pages (/firm/<slug>/) — generated by generate_firm_pages.py.
    firms_count = 0
    firm_dir = f"{OUT_DIR}/firm"
    if os.path.isdir(firm_dir):
        for slug in sorted(os.listdir(firm_dir)):
            sub = os.path.join(firm_dir, slug)
            if not os.path.isdir(sub) or not os.path.isfile(os.path.join(sub, 'index.html')): continue
            prio = "0.7" if slug == 'index.html' else "0.5"
            out.append(url_tag(f"{BASE}/firm/{slug}/", today, prio, "weekly"))
            firms_count += 1
        # /firm/ hub
        if os.path.isfile(os.path.join(firm_dir, 'index.html')):
            out.append(url_tag(f"{BASE}/firm/", today, "0.7", "weekly"))

    out.append('</urlset>\n')
    with open(f"{OUT_DIR}/sitemap.xml", "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    with open(f"{OUT_DIR}/robots.txt", "w", encoding="utf-8") as f:
        f.write("User-agent: *\nAllow: /\n\nSitemap: " + BASE + "/sitemap.xml\n")

    # Total image count for the summary line
    total_imgs = sum(len(v) for v in project_imgs.values())
    print(
        f"journal/sitemap.xml: {len(posts)} articles + 5 core pages + "
        f"{markets_count} market pages + {projects_count} project pages "
        f"(+{total_imgs} images) + {firms_count} firm pages"
    )

if __name__ == "__main__":
    main()
